apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-fault-injection
  namespace: sock-shop
spec:
  template:
    spec:
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["sh", "-c", "sleep 3600 && kubectl delete virtualservice user-abort -n sock-shop"]
      restartPolicy: Never
