apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-abort
  namespace: sock-shop
spec:
  hosts:
  - user.sock-shop.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100.0
    route:
    - destination:
        host: user.sock-shop.svc.cluster.local
