# dataset_name: "hotel-res"
# dataset_name: "online-boutique"
# dataset_name: "sock-shop"
dataset_name: "robot-shop"


# train_path: "./data/hotel-res/train/"
# train_path: "./data/online-boutique/train/"
# train_path: "./data/sock-shop/train/"
train_path: "./data/robot-shop/train/"


test_path: "./data/hotel-res/abnormal/"
output_path: "./data/hotel-res/normal/"

scaler: 'standard'

# select dimensions used to train and test
# dim:
#    from: 1
#    to: 7

algorithms:
  LSTM:
      epoch: 1
      batch_size: 32
      learning_rate: 0.01 
      seq_len: 10

  GRU:
      epoch: 1
      batch_size: 32
      learning_rate: 0.01 
      seq_len: 10

  ISST:
      dim_pos: 3

  AE:
      epoch: 5
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10

  VAE:
      epoch: 1
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10

  MLSTM:
      epoch: 1
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10
      modal:
        - 5
        - 2

  MMAE:
      epoch: 1
      batch_size: 32
      learning_rate: 0.01
      seq_len: 15
      modal:
        - 5
        - 2