# dataset_name: "hotel-res"
dataset_name: "online-boutique"
# dataset_name: "sock-shop"
# dataset_name: "robot-shop"
# dataset_name: "micro-demo"
# dataset_name: "sock-shop-wp"


# train_path: "./data/hotel-res/train/"
train_path: "./data/online-boutique/train/"
# train_path: "./data/sock-shop/train/"
# train_path: "./data/robot-shop/train/"
# train_path: "./data/micro-demo/train/"
# train_path: "./data/sock-shop-wp/train/"



test_path: "./data/hotel-res/abnormal/"
output_path: "./data/hotel-res/normal/"

scaler: 'standard'

# select dimensions used to train and test
# dim:
#    from: 1
#    to: 7

algorithms:
  LSTM:
      epoch: 100
      batch_size: 32
      learning_rate: 0.01 
      seq_len: 10

  GRU:
      epoch: 100
      batch_size: 32
      learning_rate: 0.01 
      seq_len: 10

  ISST:
      dim_pos: 3

  AE:
      epoch: 500
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10

#   VAE:
#       epoch: 1
#       batch_size: 32
#       learning_rate: 0.01
#       seq_len: 10

  MLSTM:
      epoch: 100
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10
      modal:
        - 6
        - 2

  MMAE:
      epoch: 100
      batch_size: 32
      learning_rate: 0.01
      seq_len: 15
      modal:
        - 6
        - 2