dataset_name: "online-boutique"
scaler: 'standard'

# select dimensions used to train and test
# dim:
#    from: 1
#    to: 7

algorithms:
  MLSTM:
      epoch: 10
      batch_size: 32
      learning_rate: 0.01
      seq_len: 10
      modal:
        - 4
        - 3

  MMAE:
      epoch: 10
      batch_size: 32
      learning_rate: 0.01
      seq_len: 15
      modal:
        - 4
        - 3

#   LSTM:
#       epoch: 100
#       batch_size: 32
#       learning_rate: 0.01 
#       seq_len: 10

#   GRU:
#       epoch: 100
#       batch_size: 32
#       learning_rate: 0.01 
#       seq_len: 10

#   ISST:
#       dim_pos: 3

#   AE:
#       epoch: 500
#       batch_size: 32
#       learning_rate: 0.01
#       seq_len: 10

#   VAE:
#       epoch: 1
#       batch_size: 32
#       learning_rate: 0.01
#       seq_len: 10


## 原 SCWarn 参数
#   # LSTM:
#   #     epoch: 10
#   #     batch_size: 32
#   #     learning_rate: 0.01 
#   #     seq_len: 10

#   # GRU:
#   #     epoch: 10
#   #     batch_size: 32
#   #     learning_rate: 0.01 
#   #     seq_len: 10

#   # ISST:
#   #     dim_pos: 3

#   # AE:
#   #     epoch: 50
#   #     batch_size: 32
#   #     learning_rate: 0.01
#   #     seq_len: 10

#   # VAE:
#   #     epoch: 10
#   #     batch_size: 32
#   #     learning_rate: 0.01
#   #     seq_len: 10

#   MLSTM:
#       epoch: 10
#       batch_size: 32
#       learning_rate: 0.01
#       seq_len: 10
#       modal:
#         - 4 
#         - 3

#   MMAE:
#       epoch: 10
#       batch_size: 32
#       learning_rate: 0.01
#       seq_len: 15
#       modal:
#         - 4
#         - 3