# Chaos Mesh 高强度故障注入配置
# 对 micro-demo 的各个服务进行频繁的 Pod 终止测试
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: micro-demo-aggressive-kill
  namespace: chaos-testing
spec:
  schedule: "*/1 * * * *"  # 每1分钟执行一次
  type: Workflow
  historyLimit: 5
  concurrencyPolicy: Forbid
  workflow:
    entry: entry
    templates:
      - name: entry
        templateType: Parallel
        children:
          - kill-frontend
          - kill-backend-services

      # 前端服务故障注入
      - name: kill-frontend
        templateType: PodChaos
        deadline: 45s
        podChaos:
          action: pod-kill
          mode: fixed
          value: "1"  # 同时杀死1个pod
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: front-end
          gracePeriod: 0  # 立即终止

      # 后端服务故障注入
      - name: kill-backend-services
        templateType: Parallel
        deadline: 120s
        children:
          - kill-payment
          - kill-product
          - kill-order
          - kill-cart
          - kill-user

      - name: kill-payment
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"  # 杀死50%的pods
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: payment-service
          gracePeriod: 0

      - name: kill-product
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: product-service
          gracePeriod: 0

      - name: kill-order
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: order-service
          gracePeriod: 0

      - name: kill-cart
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: cart-service
          gracePeriod: 0

      - name: kill-user
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - micro-demo
            labelSelectors:
              app: user-service
          gracePeriod: 0 