apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: microservice
  labels:
    app: gateway-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: gateway-service 