apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: your-docker-repo/gateway-service:latest
          ports:
            - containerPort: 8080 