apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservice
  labels:
    app: product-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  selector:
    app: product-service 