apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservice
  labels:
    app: user-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: user-service 