# Chaos Mesh 高强度故障注入配置
# 对 sock-shop 的各个服务进行频繁的 Pod 终止测试
apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: sock-shop-aggressive-kill
  namespace: chaos-testing
spec:
  schedule: "*/1 * * * *"  # 每1分钟执行一次
  type: Workflow
  historyLimit: 5
  concurrencyPolicy: Forbid
  workflow:
    entry: entry
    templates:
      - name: entry
        templateType: Parallel
        children:
          - kill-frontend
          - kill-backend-services
          - kill-data-services

      # 前端服务故障注入
      - name: kill-frontend
        templateType: PodChaos
        deadline: 45s
        podChaos:
          action: pod-kill
          mode: fixed
          value: "2"  # 同时杀死2个pod
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: front-end
          gracePeriod: 0  # 立即终止

      # 后端服务故障注入
      - name: kill-backend-services
        templateType: Parallel
        deadline: 120s
        children:
          - kill-cart
          - kill-catalogue
          - kill-orders
          - kill-payment
          - kill-user
          - kill-shipping

      - name: kill-cart
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"  # 杀死50%的pods
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: carts
          gracePeriod: 0

      - name: kill-catalogue
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: catalogue
          gracePeriod: 0

      - name: kill-orders
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: orders
          gracePeriod: 0

      - name: kill-payment
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: payment
          gracePeriod: 0

      - name: kill-user
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: user
          gracePeriod: 0

      - name: kill-shipping
        templateType: PodChaos
        deadline: 60s
        podChaos:
          action: pod-kill
          mode: fixed-percent
          value: "50"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: shipping
          gracePeriod: 0

      # 数据服务故障注入
      - name: kill-data-services
        templateType: Parallel
        deadline: 90s
        children:
          - kill-queue
          - kill-rabbitmq

      - name: kill-queue
        templateType: PodChaos
        deadline: 45s
        podChaos:
          action: pod-kill
          mode: fixed
          value: "1"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: queue-master
          gracePeriod: 0

      - name: kill-rabbitmq
        templateType: PodChaos
        deadline: 45s
        podChaos:
          action: pod-kill
          mode: fixed
          value: "1"
          selector:
            namespaces:
              - sock-shop
            labelSelectors:
              name: rabbitmq
          gracePeriod: 0 